### PR TITLE
fix: When the sse event is divided into multiple chunks, the sse connection is blocked

### LINKED ISSUE #2864: sse event 多chunk场景时，阻塞 event 转发
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
代理 mcp-server 时，若是上游服务通过多个 chunk 发送一个完整的 event: endpoint ，会阻塞整个 sse 连接，即encoder 会返回 api.StopAndBuffer 状态，导致一直等待数据，直到 endstream= true （即 sse 连接断开时）

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen

### PR DESCRIPTION
**Pull request by Thomas-Eliot**
### Ⅰ. Describe what this PR did
对于代理 mcp server 场景，当 上游 sse server 返回的一个event 分为多个 chunk，需要做一个缓存，且不阻塞整个 sse 后续数据的处理

### Ⅱ. Does this pull request fix one issue?

fixes #2864

### CODE REVIEW

File: plugins/golang-filter/mcp-session/filter.go [hunk 1]
```diff
@@ -289,17 +289,31 @@ func (f *filter) encodeDataFromRestUpstream(buffer api.BufferInstance, endStream
...
 		api.LogWarnf("Failed to find endpoint URL in SSE data: %v", err)
 		f.needProcess = false
 		return api.Continue
 	}
 	if endpointUrl == "" {
 		// No endpoint URL found. Need to buffer and check again.
-		return api.StopAndBuffer
+		f.cachedResponseBody = []byte(combinedData)
+		buffer.Reset()
+		return api.StopAndBufferWatermark
```
Comment (johnlanni) [inline plugins/golang-filter/mcp-session/filter.go]:
```suggestion
		return api.Continue
```
