### PR TITLE
opt(hgctl/dashboard): avoid printing error messages cannot open browser

### LINKED ISSUE #652: `hgctl dashboard` command fails on Linux without xdg-open command installed
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

`hgctl dashboard` command fails without xdg-open command installed.

### Ⅱ. Describe what happened

8b17c306605c44b608a3878e6189fcee

### Ⅲ. Describe what you expected to happen

There might be three options:
1. Show a friendly error message.
2. Open browser with something else.
3. Support port-forward only mode without opening browser directly, especially when running the command in an SSH session.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

See Ⅱ.

### Ⅵ. Environment:

- Higress version:  v1.3.1
- OS : Alibaba Cloud Linux 3.2104 LTS 64bits
- Others:

### PR DESCRIPTION
**Pull request by sjcsjc123**
### Ⅰ. Describe what this PR did

Avoid printing error messages when commands do not exist.

### Ⅱ. Does this pull request fix one issue?

fixes #652 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

This is related to the presence or absence of a GUI.

### Ⅳ. Describe how to verify it

This is executed in the centos container of Docker.

image

This is executed in local.

image

### CODE REVIEW

**Comment by CH3CHO** [comment]
Why are there only a plain URL showing in the terminal?

**Comment by sjcsjc123** [comment]
Is it okay to add and print this information?
image

**Comment by CH3CHO** [comment]
> Is it okay to add and print this information? image

Could you post a screenshot of the final output? Thanks.

**Comment by sjcsjc123** [comment]
Of course.
image

File: pkg/cmd/hgctl/dashboard.go [hunk 1]
```diff
@@ -385,3 +385,13 @@ func openBrowser(url string, writer io.Writer, browser bool) {
 		fmt.Fprintf(writer, "Failed to open browser; open %s in your browser.\nError: %s\n", url, err.Error())
 	}
 }
+
+func openCommand(command string, args ...string) error {
+	_, err := exec.LookPath(command)
+	if err != nil {
+		return nil
```
Comment (CH3CHO) [inline pkg/cmd/hgctl/dashboard.go:392]: Why don't we return `err` but a `nil` here?

**Comment by Xunzhuo** [comment]
We already have a flag for it: `--browser=false`

File: pkg/cmd/hgctl/dashboard.go (hunk 1 above)
Comment (sjcsjc123) [reply pkg/cmd/hgctl/dashboard.go:392]: When the command cannot be found, it will return err. At this time, simply print a reminder and return nil. If it returns err, there will be a step to print err later.

**Comment by sjcsjc123** [comment]
> We already have a flag for it: `--browser=false`

By default, browser is set to true, and users may not notice this flag. Running the default command without a GUI interface will also print the error. This is just my suggestion.

File: pkg/cmd/hgctl/dashboard.go (hunk 1 above)
Comment (CH3CHO) [reply pkg/cmd/hgctl/dashboard.go:393]: I think if a function cannot perform the task it claims to perform, an error should be returned. And if there is no error returned, how should we determine whether to show the corresponding message then?

Comment (sjcsjc123) [reply pkg/cmd/hgctl/dashboard.go:393]: image

How about this? If the command cannot be found, it will prompt that the browser cannot be opened; Otherwise, return err.

Comment (CH3CHO) [reply pkg/cmd/hgctl/dashboard.go:393]: LGTM

Comment (CH3CHO) [reply pkg/cmd/hgctl/dashboard.go:393]: Which one is better?
1. Display an error message in openCommand and return nil
2. Return an error in openCommand function and show the corresponding error message in the caller

Comment (sjcsjc123) [reply pkg/cmd/hgctl/dashboard.go:393]: I tend to print it out in the opencommand method and then change it to a method with no return parameters.

**Review by Xunzhuo — APPROVED** [review]
Current approach looks good, this is an opt on error msg but not a bug fix.
